import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppNavbar } from "~/components/containers/AppNavbar";
import { AppProviders } from "~/components/providers";
import "./globals.css";
import { SidebarProvider } from "~/components/ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = { description: "Generated by create next app", title: "Create Next App" };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className="dark" lang="en" style={{ colorScheme: "dark" }}>
      <body className={inter.className}>
        <AppProviders>
          <SidebarProvider>
            <div className="flex min-h-screen w-full flex-col items-center">
              <AppNavbar />

              <div className="mx-auto flex w-full max-w-screen-lg gap-4 pt-[calc(var(--navbar-height)+4rem)]">
                {children}
              </div>
            </div>
          </SidebarProvider>
        </AppProviders>
      </body>
    </html>
  );
}
