import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavigationBar } from "~/components/containers/NavigationBar";
import { AppProviders } from "~/components/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = { description: "Generated by create next app", title: "Create Next App" };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className="dark" lang="en" style={{ colorScheme: "dark" }}>
      <body className={inter.className}>
        <AppProviders>
          <div className="mx-auto max-w-[800px]">
            <NavigationBar />
            <div className="flex items-center justify-center">{children}</div>
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
