/** @deprecated Use getRPCUrl or RPC_URLS instead */
export enum RPCUrl {
  Arbitrum = "https://arb1.arbitrum.io/rpc",
  Avalanche = "https://avalanche-c-chain-rpc.publicnode.com",
  Base = "https://base.llamarpc.com",
  BinanceSmartChain = "https://bsc-dataseed.binance.org",
  Bitcoin = "https://bitcoin-rpc.publicnode.com",
  BitcoinCash = "https://node-router.thorswap.net/bitcoin-cash",
  Chainflip = "wss://mainnet-archive.chainflip.io",
  Cosmos = "https://node-router.thorswap.net/cosmos/rpc",
  Dash = "https://dash-rpc.publicnode.com",
  Dogecoin = "https://node-router.thorswap.net/dogecoin",
  Ethereum = "https://ethereum-rpc.publicnode.com",
  Kujira = "https://rpc-kujira.synergynodes.com/",
  Litecoin = "https://node-router.thorswap.net/litecoin",
  Maya = "https://tendermint.mayachain.info",
  MayaStagenet = "https://stagenet.tendermint.mayachain.info",
  Optimism = "https://mainnet.optimism.io",
  Polkadot = "wss://rpc.polkadot.io",
  Polygon = "https://polygon-rpc.com",
  Radix = "https://radix-mainnet.rpc.grove.city/v1/326002fc/core",
  THORChain = "https://rpc.thorswap.net",
  THORChainStagenet = "https://stagenet-rpc.ninerealms.com",
  Solana = "https://solana-rpc.publicnode.com",
}

/** @deprecated Use EXPLORER_URLS instead */
export enum ExplorerUrl {
  Arbitrum = "https://arbiscan.io",
  Avalanche = "https://snowtrace.io",
  Base = "https://basescan.org",
  BinanceSmartChain = "https://bscscan.com",
  Bitcoin = "https://blockchair.com/bitcoin",
  BitcoinCash = "https://www.blockchair.com/bitcoin-cash",
  Chainflip = "https://explorer.polkascan.io/polkadot",
  Cosmos = "https://www.mintscan.io/cosmos",
  Dash = "https://blockchair.com/dash",
  Dogecoin = "https://blockchair.com/dogecoin",
  Ethereum = "https://etherscan.io",
  Kujira = "https://finder.kujira.network/kaiyo-1",
  Litecoin = "https://blockchair.com/litecoin",
  Maya = "https://www.mayascan.org",
  Optimism = "https://optimistic.etherscan.io",
  Polkadot = "https://polkadot.subscan.io",
  Polygon = "https://polygonscan.com",
  Radix = "https://dashboard.radixdlt.com",
  THORChain = "https://runescan.io",
  Solana = "https://solscan.io",
}
