export enum Chain {
  Arbitrum = "ARB",
  Aurora = "AURORA",
  Avalanche = "AVAX",
  Base = "BASE",
  Berachain = "BERA",
  BinanceSmartChain = "BSC",
  Bitcoin = "BTC",
  BitcoinCash = "BCH",
  Cosmos = "GAIA",
  Dash = "DASH",
  Dogecoin = "DOGE",
  Ethereum = "ETH",
  Fiat = "FIAT",
  Gnosis = "GNO",
  Kujira = "KUJI",
  Litecoin = "LTC",
  Maya = "MAYA",
  Near = "NEAR",
  Noble = "NOBLE",
  Optimism = "OP",
  Polkadot = "DOT",
  Chainflip = "FLIP",
  Polygon = "POL",
  Radix = "XRD",
  Ripple = "XRP",
  THORChain = "THOR",
  Solana = "SOL",
  Tron = "TRON",
  Zcash = "ZEC",
}

export enum StagenetChain {
  THORChain = "THOR_STAGENET",
  Maya = "MAYA_STAGENET",
}

export enum ChainId {
  ARB = "42161",
  AURORA = "1313161554",
  AVAX = "43114",
  BASE = "8453",
  BERA = "80094",
  BSC = "56",
  BTC = "bitcoin",
  BCH = "bitcoincash",
  FLIP = "chainflip",
  GAIA = "cosmoshub-4",
  DASH = "dash",
  DOGE = "dogecoin",
  ETH = "1",
  FIAT = "fiat",
  GNO = "100",
  KUJI = "kaiyo-1",
  LTC = "litecoin",
  MAYA = "mayachain-mainnet-v1",
  NEAR = "near",
  NOBLE = "noble-1",
  OP = "10",
  DOT = "polkadot",
  POL = "137",
  XRD = "radix-mainnet",
  XRP = "ripple",
  THOR = "thorchain-1",
  SOL = "solana",
  TRON = "728126428",
  ZEC = "zcash",

  // Stagenet chains
  THOR_STAGENET = "thorchain-stagenet-v2",
  MAYA_STAGENET = "mayachain-stagenet-v1",
}

// export enum ChainId {
//   Arbitrum = "42161",
//   ArbitrumHex = "0xa4b1",
//   Aurora = "1313161554",
//   AuroraHex = "0x4e454152",
//   Avalanche = "43114",
//   AvalancheHex = "0xa86a",
//   Base = "8453",
//   BaseHex = "0x2105",
//   Berachain = "80094",
//   BerachainHex = "0x138de",
//   BinanceSmartChain = "56",
//   BinanceSmartChainHex = "0x38",
//   Bitcoin = "bitcoin",
//   BitcoinCash = "bitcoincash",
//   Chainflip = "chainflip",
//   Cosmos = "cosmoshub-4",
//   Dash = "dash",
//   Dogecoin = "dogecoin",
//   Ethereum = "1",
//   EthereumHex = "0x1",
//   Fiat = "fiat",
//   Gnosis = "100",
//   GnosisHex = "0x64",
//   Kujira = "kaiyo-1",
//   Litecoin = "litecoin",
//   Maya = "mayachain-mainnet-v1",
//   MayaStagenet = "mayachain-stagenet-v1",
//   Near = "near",
//   Noble = "noble-1",
//   Optimism = "10",
//   OptimismHex = "0xa",
//   Polkadot = "polkadot",
//   Polygon = "137",
//   PolygonHex = "0x89",
//   Radix = "radix-mainnet",
//   Ripple = "ripple",
//   THORChain = "thorchain-1",
//   THORChainStagenet = "thorchain-stagenet-v2",
//   Solana = "solana",
//   Tron = "728126428",
//   TronHex = "0x2b6653dc",
//   Zcash = "zcash",
// }
